package dsw.rudok.app.errorhandler;

public enum ErrorType {
    NO_NODE_SELECTED, WORKSPACE_DELETION, NO_FRAME_SELECTED,
    NO_SHAPE_SELECTED, NO_CLICK_ON_SHAPE, NO_FRAME_CREATED, NO_DOCUMENT_SELECTED, NO_PROJECT_SELECTED,
    NO_UNDO_REMAINING, NO_REDO_REMAINING
}
