version: '3.7'

services:
  ui:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm start
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
  storybook:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run storybook
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - "6006:6006"
    environment:
      - CHOKIDAR_USEPOLLING=true
